#!/bin/sh

# Slackware build script for dokuwiki
# Written by David Spencer <baildon.research@googlemail.com>
# This script is dedicated to the public domain

PRGNAM=dokuwiki
VERSION=${VERSION:-2011_05_25}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

SRCVER=$(echo $VERSION | tr _ - )

ARCH=noarch

DOCROOT=${DOCROOT:-/var/www/htdocs}
PHPUSER=${PHPUSER:-apache}
PHPGROUP=${PHPGROUP:-apache}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$SRCVER
tar xvf $CWD/$PRGNAM-$SRCVER.tgz
cd $PRGNAM-$SRCVER
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Change install paths to conform to Slackware norms and dokuwiki's own security advice
patch -p1 < $CWD/dokuwiki-installpaths.patch

mkdir -p $PKG/$DOCROOT/$PRGNAM
cp -a \
  inc/ lib/ \
  .htaccess.dist doku.php feed.php index.php install.php \
  $PKG/$DOCROOT/$PRGNAM
chown -R $PHPUSER:$PHPGROUP \
  $PKG/$DOCROOT/$PRGNAM/lib/plugins

mkdir -p $PKG/var/lib/$PRGNAM
chown root:$PHPGROUP $PKG/var/lib/$PRGNAM
cp -a \
  conf/ data/ \
  $PKG/var/lib/$PRGNAM
chown -R $PHPUSER:$PHPGROUP \
  $PKG/var/lib/$PRGNAM/conf \
  $PKG/var/lib/$PRGNAM/data
chmod -R o-rwx $PKG/var/lib/$PRGNAM

mkdir -p $PKG/usr/bin
cp -a \
  bin/* \
  $PKG/usr/bin

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  COPYING README \
  $PKG/usr/doc/$PRGNAM-$VERSION

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh
( cd $PKG/var/lib/$PRGNAM/conf
  for i in *.conf *.php; do
    mv $i $i.new
    echo "config var/lib/$PRGNAM/conf/$i.new" >> $PKG/install/doinst.sh
  done
)
# Stop any confusing upgrade msg (http://www.dokuwiki.org/update_check)
echo "rm -f /var/lib/dokuwiki/data/cache/messages.txt" >> $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
