#!/bin/sh

# NOTE: This SlackBuild script is UNMAINTAINED.

# Slackware build script for xtrkcad
# Written by David Spencer <baildon.research@googlemail.com>
# This script is dedicated to the public domain

# Modified by Robby Workman <rworkman@slackbuilds.org>

PRGNAM=xtrkcad
SRCNAM=xtrkcad-source
VERSION=${VERSION:-4.0.3a}
BUILD=${BUILD:-1}
TAG=${TAG:-_unm}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM-$VERSION
tar xvf $CWD/$SRCNAM-$VERSION.tar.gz
cd $SRCNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

cmake \
  -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DXTRKCAD_USE_GTK=ON \
  -DXTRKCAD_USE_GTK_CAIRO=ON \
  .

make
make install DESTDIR=$PKG

strip --strip-unneeded $PKG/usr/bin/xtrkcad

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a app/COPYING app/doc/ChangeLog app/lib/Readme.txt \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
