#!/bin/sh

# Slackware build script for JMRI
# Written by David Spencer <baildon.research@googlemail.com>
# This script is dedicated to the public domain

PRGNAM=jmri
VERSION=${VERSION:-2.10}
ARCH=i486  # due to certain embedded libraries
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

TARNAM=JMRI

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $TARNAM
tar xvf $CWD/$TARNAM.$VERSION.tgz
cd $TARNAM
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mkdir -p $PKG/usr/bin
cp -a \
  DecoderPro InstallTest JmriDemo LocoTools PanelPro SoundPro cornwall \
  $PKG/usr/bin
chmod 755 $PKG/usr/bin/*

mkdir -p $PKG/opt/jmri
cp -a \
  default.lcf help/ jmri.jar lib/ resources/ xml/ \
  $PKG/opt/jmri

# Let's not abuse writability in /opt
mkdir -p $PKG/var/lib/jmri/
cp -a jython $PKG/var/lib/jmri
chmod 1777 $PKG/var/lib/jmri/jython
( cd $PKG/opt/jmri ; ln -s ../../var/lib/jmri/jython . )
#
mkdir -p $PKG/var/lib/jmri/cachedir/packages
chmod 1777 $PKG/var/lib/jmri/cachedir/packages
( cd $PKG/opt/jmri/lib ; ln -s ../../../var/lib/jmri/cachedir . )
#
mkdir -p $PKG/var/log/jmri
touch $PKG/var/log/jmri/messages.log.new
chmod 666 $PKG/var/log/jmri/messages.log.new
( cd $PKG/opt/jmri ; ln -s ../../var/log/jmri/messages.log . )

# Install some profile scripts for shell init
mkdir -p $PKG/etc/profile.d
cat $CWD/jmri.sh  > $PKG/etc/profile.d/jmri.sh
cat $CWD/jmri.csh > $PKG/etc/profile.d/jmri.csh
chmod 755 $PKG/etc/profile.d/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  COPYING \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/usr/share/applications
install -m 0644 -t $PKG/usr/share/applications \
  $CWD/DecoderPro.desktop \
  $CWD/PanelPro.desktop \
  $CWD/SoundPro.desktop
mkdir -p $PKG/usr/share/pixmaps
install -m 0644 -t $PKG/usr/share/pixmaps \
  $CWD/jmri.png

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh  > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
